# Cloud Run service configuration
service: edu-support-ai-system

runtime: custom

# Environment variables
env_variables:
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  CORS_ORIGINS: "*"
  SESSION_EXPIRATION_SECONDS: "3600"
  DEFAULT_PAGE_SIZE: "20"
  MAX_PAGE_SIZE: "100"
  ALLOW_ALL_API_KEYS: "false"
  # Set VALID_API_KEYS via Secret Manager or gcloud run services update
  # VALID_API_KEYS: "your-production-keys-here"

  # Google API Configuration
  # Set GOOGLE_API_KEY via Secret Manager for security
  # GOOGLE_API_KEY: "your-google-api-key"

  # Database Configuration
  # Set DATABASE_URL via Secret Manager or gcloud run services update
  # DATABASE_URL: "postgresql://user:password@host:5432/database"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.7
  target_concurrent_requests: 80

# Resource configuration
resources:
  cpu: 1
  memory_gb: 0.5

# Health check
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3

readiness_check:
  path: "/health"
  check_interval_sec: 10
  timeout_sec: 10
  failure_threshold: 3
